-- v1.0
minetest.register_alias("compressed leaves lv1", "dirtandwater:comp_leaves1")
minetest.register_alias("compressed leaves lv2", "dirtandwater:comp_leaves2")
minetest.register_alias("compressed leaves lv3", "dirtandwater:comp_leaves3")
minetest.register_alias("Glowing leaves", "dirtandwater:glow_l_frame")
minetest.register_alias("Glowing gold leaves", "dirtandwater:glow_gold_l")
minetest.register_alias("Glowing steel leaves", "dirtandwater:steel_glow_l_l")
minetest.register_alias("compressed leaves stairs", "dirtandwater:leave_stairs")
minetest.register_alias("compressed leaves slab", "dirtandwater:leave_slab")
minetest.register_alias("compressed leaves table", "dirtandwater:comp_leave_table")
minetest.register_alias("compressed leaves wall", "dirtandwater:leave_wall")
minetest.register_alias("compressed leaves chair", "dirtandwater:leave_chair")
-- v1.0.1
minetest.register_alias("Leaves shelf", "dirtandwater:leave_shelf")
minetest.register_alias("Leaves half shelf", "dirtandwater:leave_half_shelf")
minetest.register_alias("Leaves chest", "dirtandwater:chest")
minetest.register_alias("Leaves down half shelf", "dirtandwater:leave_dhalf_shelf")
minetest.register_alias("Leaves cabinet", "dirtandwater:leaves_cabinet")
minetest.register_alias("Leaves half cabinet", "dirtandwater:leave_half_cabinet")
minetest.register_alias("Leaves small box", "dirtandwater:leaves_small_box")
minetest.register_alias("Leaves cabinet bottom", "dirtandwater:leaves_cabinet2")
minetest.register_alias("Leaves half cabinet bottom", "dirtandwater:leave_half_cabinet_b")